# Generated by Django 6.0.1 on 2026-01-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=200, verbose_name='Marca')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='supplements/', verbose_name='imagen')),
                ('flavor', models.CharField(blank=True, null=True, verbose_name='sabor')),
                ('quantity_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade disponivel')),
                ('product_content_size', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='tamanho do conteúdo do produto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descricao')),
            ],
        ),
    ]
