# Generated by Django 6.0.1 on 2026-01-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0002_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplements',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplement_brand', to='supplements.brand', verbose_name='Marca'),
        ),
    ]
