# Generated by Django 6.0.1 on 2026-01-24 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0004_flavor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_content_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='supplements',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplement_flavor', to='supplements.flavor', verbose_name='sabor'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='product_content_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplement_content_size', to='supplements.product_content_size', verbose_name='tamanho do conteudo'),
        ),
    ]
