# Generated by Django 6.0.1 on 2026-01-24 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0005_product_content_size_alter_supplements_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplements',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplement_flavor', to='supplements.flavor', verbose_name='sabor'),
        ),
    ]
