# Generated by Django 6.0.1 on 2026-01-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0006_alter_supplements_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplements',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
