# Generated by Django 6.0.1 on 2026-01-30 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0007_supplements_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='supplements',
            name='size',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplement_size', to='supplements.size', verbose_name='Tamanho'),
        ),
    ]
