# Generated by Django 6.0.1 on 2026-01-30 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0009_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplements',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplement_flavor', to='supplements.flavor', verbose_name='sabor'),
        ),
    ]
