# Generated by Django 6.0.1 on 2026-01-30 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0010_alter_supplements_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplements',
            name='product_content_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplement_content_size', to='supplements.product_content_size', verbose_name='tamanho do conteudo'),
        ),
    ]
