# Generated by Django 6.0.1 on 2026-02-08 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0011_alter_supplements_product_content_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSupplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Supplements/')),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='supplements.supplements')),
            ],
        ),
    ]
