# Generated by Django 6.0.1 on 2026-02-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0012_imagesupplement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplements',
            name='photo',
        ),
    ]
