# Generated by Django 6.0.1 on 2026-02-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0013_remove_supplements_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='imagen do banner. sugestao: 1920x500 ou 1600x450', upload_to='home_banners/')),
                ('headline', models.CharField(blank=True, help_text='Texto opcional do banner (se quiser mostrar em cima).', max_length=100)),
                ('link', models.URLField(blank=True, help_text='Link opcional. Se preencher, ao clicar no banner vai abrir esse link.')),
                ('order', models.PositiveBigIntegerField(default=1, help_text='Ordem de exibição (1, 2, 3).')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativar, esse banner não aparece no site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
