# Generated by Django 6.0.1 on 2026-02-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0015_category_supplements_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplements',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplements', to='supplements.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplements', to='supplements.category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplements', to='supplements.flavor', verbose_name='sabor'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='product_content_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplements', to='supplements.product_content_size', verbose_name='tamanho do conteudo'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='size',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplements', to='supplements.size', verbose_name='Tamanho'),
        ),
    ]
