# Generated by Django 6.0.1 on 2026-02-28 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0016_alter_supplements_brand_alter_supplements_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplements',
            name='total_visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
