# Generated by Django 6.0.1 on 2026-02-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0017_supplements_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplements',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='total_visualizacoes',
        ),
    ]
