# Generated by Django 6.0.1 on 2026-03-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0020_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
