# Generated by Django 6.0.1 on 2026-03-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0027_alter_category_options_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplements',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='price',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='product_content_size',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='quantity_stock',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='size',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('quantity_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade disponivel')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='supplements.brand', verbose_name='Marca')),
                ('flavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='supplements.flavor', verbose_name='sabor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='supplements.supplements')),
                ('product_content_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='supplements.product_content_size', verbose_name='tamanho do conteudo')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='supplements.size', verbose_name='Tamanho')),
            ],
        ),
    ]
