# Generated by Django 6.0.1 on 2026-03-26 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0029_remove_supplements_category_productvariant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='category',
        ),
        migrations.AddField(
            model_name='supplements',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplements', to='supplements.category', verbose_name='categoria'),
        ),
    ]
