# Generated by Django 6.0.1 on 2026-03-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0031_remove_orderitem_product_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='supplements.flavor', verbose_name='Sabor'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product_content_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='supplements.product_content_size', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='quantity_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplements', to='supplements.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
