# Generated by Django 6.0.1 on 2026-04-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0033_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
