# Generated by Django 6.0.1 on 2026-05-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0034_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='brand',
        ),
    ]
