# Generated by Django 6.0.1 on 2026-05-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0035_remove_productvariant_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplements',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplements', to='supplements.brand'),
        ),
    ]
