# Generated by Django 6.0.1 on 2026-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0037_alter_productvariant_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Nome da campanha')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desconto (%)')),
                ('banner_text', models.CharField(max_length=255, verbose_name='Texto do banner')),
                ('badge_text', models.CharField(default='OFF', max_length=50, verbose_name='Texto da etiqueta')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
