# Generated by Django 6.0.1 on 2026-06-21 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0038_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Informe apenas o número. Ex.: 15 para 15%.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto (%)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(help_text='Ex.: Black Friday, Dia das Mães...', max_length=120, verbose_name='Nome da campanha'),
        ),
    ]
