# Generated by Django 6.0.1 on 2026-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0039_alter_campaign_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='image',
        ),
        migrations.AddField(
            model_name='homebanner',
            name='desktop_image',
            field=models.ImageField(blank=True, help_text='Banner para desktop (sugestão: 1920×700).', null=True, upload_to='home_banners/desktop/'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Banner para celular (sugestão: 1080×1350). Se não preencher, será usada a imagem desktop.', null=True, upload_to='home_banners/mobile/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='headline',
            field=models.CharField(blank=True, help_text='Texto opcional do banner.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se desativar, esse banner não aparece.'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='link',
            field=models.URLField(blank=True, help_text='Link opcional.'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Ordem de exibição.'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
